"""add activity_logs and coach_insights tables

Revision ID: 436df366a6fc
Revises: c4c16e8ad2c8
Create Date: 2025-12-08 19:36:00.502247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '436df366a6fc'
down_revision: Union[str, None] = 'c4c16e8ad2c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_type'), 'activity_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_table('coach_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ACTION', 'TIME', 'PATTERN', name='insighttype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='insightpriority'), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('suggested_action', sa.String(length=100), nullable=True),
    sa.Column('action_params', sa.JSON(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('seen', sa.Boolean(), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_insights_created_at'), 'coach_insights', ['created_at'], unique=False)
    op.create_index(op.f('ix_coach_insights_dismissed'), 'coach_insights', ['dismissed'], unique=False)
    op.create_index(op.f('ix_coach_insights_id'), 'coach_insights', ['id'], unique=False)
    op.create_index(op.f('ix_coach_insights_seen'), 'coach_insights', ['seen'], unique=False)
    op.create_index(op.f('ix_coach_insights_type'), 'coach_insights', ['type'], unique=False)
    #     op.alter_column('crm_deals', 'billing_frequency',
    #                existing_type=sa.VARCHAR(length=20),
    #                type_=sa.Enum('MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL', name='billingfrequency'),
    #                existing_nullable=True)
    #     op.alter_column('crm_deals', 'service_status',
    #                existing_type=sa.VARCHAR(length=20),
    #                type_=sa.Enum('ACTIVE', 'PAUSED', 'CANCELLED', 'PENDING', name='servicestatus'),
    #                existing_nullable=True)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    #     op.alter_column('time_entries', 'category',
    #                existing_type=sa.VARCHAR(length=20),
    #                type_=sa.Enum('DEVELOPMENT', 'DESIGN', 'MEETING', 'COMMUNICATION', 'RESEARCH', 'ADMIN', 'SUPPORT', 'OTHER', name='timeentrycategory'),
    #                existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_entries', 'category',
               existing_type=sa.Enum('DEVELOPMENT', 'DESIGN', 'MEETING', 'COMMUNICATION', 'RESEARCH', 'ADMIN', 'SUPPORT', 'OTHER', name='timeentrycategory'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.alter_column('crm_deals', 'service_status',
               existing_type=sa.Enum('ACTIVE', 'PAUSED', 'CANCELLED', 'PENDING', name='servicestatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('crm_deals', 'billing_frequency',
               existing_type=sa.Enum('MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL', name='billingfrequency'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_coach_insights_type'), table_name='coach_insights')
    op.drop_index(op.f('ix_coach_insights_seen'), table_name='coach_insights')
    op.drop_index(op.f('ix_coach_insights_id'), table_name='coach_insights')
    op.drop_index(op.f('ix_coach_insights_dismissed'), table_name='coach_insights')
    op.drop_index(op.f('ix_coach_insights_created_at'), table_name='coach_insights')
    op.drop_table('coach_insights')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
