"""Add recurrence_days to tasks

Revision ID: 53ca47e97ba5
Revises: 9f4b79dbf4f7
Create Date: 2025-11-19 17:07:30.428230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ca47e97ba5'
down_revision: Union[str, None] = '9f4b79dbf4f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('crm_contacts', 'lead_source',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=100),
    #            existing_nullable=True)
    # op.alter_column('crm_interactions', 'type',
    #            existing_type=sa.VARCHAR(length=7),
    #            type_=sa.Enum('MEETING', 'EMAIL', 'CALL', 'NOTE', 'SOCIAL_MEDIA', name='interactiontype'),
    #            existing_nullable=False)
    op.add_column('tasks', sa.Column('recurrence_days', sa.String(length=255), nullable=True))
    # op.create_foreign_key(None, 'tasks', 'goals', ['goal_id'], ['id'], ondelete='SET NULL')
    # op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'])
    # op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'recurrence_days')
    op.alter_column('crm_interactions', 'type',
               existing_type=sa.Enum('MEETING', 'EMAIL', 'CALL', 'NOTE', 'SOCIAL_MEDIA', name='interactiontype'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.alter_column('crm_contacts', 'lead_source',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
