"""add_recurring_tasks_fields

Revision ID: 6bd44376f2f7
Revises: 4cfc13de995a
Create Date: 2025-11-14 17:43:53.666739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd44376f2f7'
down_revision: Union[str, None] = '4cfc13de995a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip alter_column for SQLite compatibility - these are not critical changes
    # op.alter_column('crm_contacts', 'lead_source',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=100),
    #            existing_nullable=True)
    # op.alter_column('crm_interactions', 'type',
    #            existing_type=sa.VARCHAR(length=7),
    #            type_=sa.Enum('MEETING', 'EMAIL', 'CALL', 'NOTE', 'SOCIAL_MEDIA', name='interactiontype'),
    #            existing_nullable=False)

    # Add goal_id column first if it doesn't exist
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        try:
            batch_op.add_column(sa.Column('goal_id', sa.Integer(), nullable=True))
        except:
            pass  # Column might already exist

    # Add recurring task fields
    op.add_column('tasks', sa.Column('is_recurring', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('tasks', sa.Column('recurrence_type', sa.String(20), nullable=True))
    op.add_column('tasks', sa.Column('recurrence_interval', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('recurrence_end_date', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('recurrence_count', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('occurrences_created', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('tasks', sa.Column('parent_task_id', sa.Integer(), nullable=True))

    # Only create index if it doesn't exist
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        try:
            batch_op.create_index(batch_op.f('ix_tasks_goal_id'), ['goal_id'], unique=False)
        except:
            pass  # Index might already exist

    # Create foreign keys if they don't exist
    try:
        op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'])
    except:
        pass

    try:
        op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task_id'], ['id'])
    except:
        pass

    try:
        op.create_foreign_key(None, 'tasks', 'goals', ['goal_id'], ['id'], ondelete='SET NULL')
    except:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop recurring task fields
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        try:
            batch_op.drop_column('parent_task_id')
        except:
            pass
        try:
            batch_op.drop_column('occurrences_created')
        except:
            pass
        try:
            batch_op.drop_column('recurrence_count')
        except:
            pass
        try:
            batch_op.drop_column('recurrence_end_date')
        except:
            pass
        try:
            batch_op.drop_column('recurrence_interval')
        except:
            pass
        try:
            batch_op.drop_column('recurrence_type')
        except:
            pass
        try:
            batch_op.drop_column('is_recurring')
        except:
            pass
    # ### end Alembic commands ###
