"""add social content table

Revision ID: 9f4b79dbf4f7
Revises: 6bd44376f2f7
Create Date: 2025-11-18 15:03:31.989242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4b79dbf4f7'
down_revision: Union[str, None] = '6bd44376f2f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_date', sa.Date(), nullable=False),
    sa.Column('content_type', sa.Enum('REEL', 'CAROUSEL', 'SINGLE_POST', 'STORY', 'TIKTOK', 'YOUTUBE_SHORT', 'YOUTUBE_VIDEO', 'BLOG_POST', name='contenttype'), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'SCRIPTED', 'FILMED', 'EDITING', 'SCHEDULED', 'POSTED', name='contentstatus'), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('editing_style', sa.Enum('FAST_PACED', 'CINEMATIC', 'EDUCATIONAL', 'BEHIND_SCENES', 'TRENDING', 'TUTORIAL', 'INTERVIEW', 'CUSTOM', name='editingstyle'), nullable=True),
    sa.Column('editing_notes', sa.Text(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('music_audio', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_reference', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_content_content_date'), 'social_content', ['content_date'], unique=False)
    op.create_index(op.f('ix_social_content_id'), 'social_content', ['id'], unique=False)
    op.add_column('crm_contacts', sa.Column('lead_source', sa.String(length=100), nullable=True))
    op.drop_column('crm_contacts', 'source')
    op.add_column('crm_deals', sa.Column('next_followup_date', sa.Date(), nullable=True))
    op.drop_index('ix_tasks_project_id', table_name='tasks')
    op.create_index(op.f('ix_tasks_goal_id'), 'tasks', ['goal_id'], unique=False)
    # SQLite doesn't support adding foreign keys with ALTER, so we wrap in batch_alter_table
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        try:
            batch_op.create_foreign_key('fk_tasks_goal_id', 'goals', ['goal_id'], ['id'], ondelete='SET NULL')
        except:
            pass
        try:
            batch_op.create_foreign_key('fk_tasks_parent_task_id', 'tasks', ['parent_task_id'], ['id'])
        except:
            pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_goal_id'), table_name='tasks')
    op.create_index('ix_tasks_project_id', 'tasks', ['project_id'], unique=False)
    op.drop_column('crm_deals', 'next_followup_date')
    op.add_column('crm_contacts', sa.Column('source', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('crm_contacts', 'lead_source')
    op.drop_index(op.f('ix_social_content_id'), table_name='social_content')
    op.drop_index(op.f('ix_social_content_content_date'), table_name='social_content')
    op.drop_table('social_content')
    # ### end Alembic commands ###
