"""add cta_used and angle_used to experiments

Revision ID: bfde976fca14
Revises: 23d5e8e2861d
Create Date: 2026-03-28 13:37:21.894397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfde976fca14'
down_revision: Union[str, None] = '23d5e8e2861d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_coach_insights_created_at', table_name='coach_insights')
    op.drop_index('ix_coach_insights_dismissed', table_name='coach_insights')
    op.drop_index('ix_coach_insights_id', table_name='coach_insights')
    op.drop_index('ix_coach_insights_seen', table_name='coach_insights')
    op.drop_index('ix_coach_insights_type', table_name='coach_insights')
    op.drop_table('coach_insights')
    op.alter_column('crm_deals', 'billing_frequency',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL', name='billingfrequency'),
               existing_nullable=True)
    op.alter_column('crm_deals', 'service_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVE', 'PAUSED', 'CANCELLED', 'PENDING', name='servicestatus'),
               existing_nullable=True)
    op.create_index(op.f('ix_crm_deals_contact_id'), 'crm_deals', ['contact_id'], unique=False)
    op.create_index(op.f('ix_crm_interactions_contact_id'), 'crm_interactions', ['contact_id'], unique=False)
    op.drop_index('ix_discovery_calls_call_date', table_name='discovery_calls')
    op.alter_column('email_matches', 'from_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('email_matches', 'to_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('email_matches', 'received_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_email_opens_id'), 'email_opens', ['id'], unique=False)
    op.add_column('experiments', sa.Column('cta_used', sa.String(length=500), nullable=True))
    op.add_column('experiments', sa.Column('angle_used', sa.String(length=100), nullable=True))
    op.alter_column('experiments', 'step_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('experiments_audit_id_fkey', 'experiments', type_='foreignkey')
    op.create_foreign_key(None, 'experiments', 'audit_results', ['audit_id'], ['id'], ondelete='SET NULL')
    op.alter_column('insights', 'confidence',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('insights', 'sample_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_loom_audits_sent_date', table_name='loom_audits')
    op.alter_column('outreach_campaigns', 'campaign_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('EMAIL', 'LINKEDIN', 'MULTI_TOUCH', name='campaigntype'),
               existing_nullable=False,
               existing_server_default=sa.text("'EMAIL'::character varying"))
    op.alter_column('outreach_campaigns', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVE', 'ARCHIVED', name='campaignstatus'),
               existing_nullable=True)
    op.alter_column('outreach_prospects', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('QUEUED', 'IN_SEQUENCE', 'REPLIED', 'NOT_INTERESTED', 'CONVERTED', 'SKIPPED', 'PENDING_CONNECTION', 'CONNECTED', 'PENDING_ENGAGEMENT', name='prospectstatus'),
               existing_nullable=True)
    op.alter_column('outreach_prospects', 'response_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('INTERESTED', 'NOT_INTERESTED', 'OTHER', name='responsetype'),
               existing_nullable=True)
    op.drop_index('ix_outreach_prospects_status', table_name='outreach_prospects')
    op.drop_index('uq_campaign_email', table_name='outreach_prospects', postgresql_where="((email IS NOT NULL) AND ((email)::text <> ''::text))")
    op.create_foreign_key(None, 'outreach_prospects', 'crm_deals', ['converted_deal_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'outreach_prospects', 'crm_contacts', ['converted_contact_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'outreach_prospects', 'discovered_leads', ['discovered_lead_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_outreach_templates_niche_id'), 'outreach_templates', ['niche_id'], unique=False)
    op.create_index(op.f('ix_outreach_templates_situation_id'), 'outreach_templates', ['situation_id'], unique=False)
    op.alter_column('project_template_tasks', 'priority',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('project_template_tasks', 'order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_project_template_tasks_id'), 'project_template_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_project_templates_id'), 'project_templates', ['id'], unique=False)
    op.create_index(op.f('ix_projects_contact_id'), 'projects', ['contact_id'], unique=False)
    op.create_index(op.f('ix_search_planner_combinations_id'), 'search_planner_combinations', ['id'], unique=False)
    op.alter_column('social_content', 'reel_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('EDUCATIONAL', 'BEFORE_AFTER', 'BTS', 'SOCIAL_PROOF', 'MINI_AUDIT', 'SEO_EDUCATION', 'CLIENT_RESULTS', 'DIRECT_CTA', 'FULL_REDESIGN', name='reeltype'),
               existing_nullable=True)
    op.drop_index('ix_sprint_days_day_number', table_name='sprint_days')
    op.drop_index('ix_sprint_days_log_date', table_name='sprint_days')
    op.drop_index('ix_sprints_status', table_name='sprints')
    op.create_index(op.f('ix_task_links_id'), 'task_links', ['id'], unique=False)
    op.create_index(op.f('ix_task_notes_id'), 'task_notes', ['id'], unique=False)
    op.alter_column('tasks', 'recurrence_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='recurrencetype'),
               existing_nullable=True)
    op.alter_column('time_entries', 'category',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DEVELOPMENT', 'DESIGN', 'MEETING', 'COMMUNICATION', 'RESEARCH', 'ADMIN', 'SUPPORT', 'OTHER', name='timeentrycategory'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_entries', 'category',
               existing_type=sa.Enum('DEVELOPMENT', 'DESIGN', 'MEETING', 'COMMUNICATION', 'RESEARCH', 'ADMIN', 'SUPPORT', 'OTHER', name='timeentrycategory'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('tasks', 'recurrence_type',
               existing_type=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='recurrencetype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_task_notes_id'), table_name='task_notes')
    op.drop_index(op.f('ix_task_links_id'), table_name='task_links')
    op.create_index('ix_sprints_status', 'sprints', ['status'], unique=False)
    op.create_index('ix_sprint_days_log_date', 'sprint_days', ['log_date'], unique=False)
    op.create_index('ix_sprint_days_day_number', 'sprint_days', ['day_number'], unique=False)
    op.alter_column('social_content', 'reel_type',
               existing_type=sa.Enum('EDUCATIONAL', 'BEFORE_AFTER', 'BTS', 'SOCIAL_PROOF', 'MINI_AUDIT', 'SEO_EDUCATION', 'CLIENT_RESULTS', 'DIRECT_CTA', 'FULL_REDESIGN', name='reeltype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_search_planner_combinations_id'), table_name='search_planner_combinations')
    op.drop_index(op.f('ix_projects_contact_id'), table_name='projects')
    op.drop_index(op.f('ix_project_templates_id'), table_name='project_templates')
    op.drop_index(op.f('ix_project_template_tasks_id'), table_name='project_template_tasks')
    op.alter_column('project_template_tasks', 'order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('project_template_tasks', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'),
               type_=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.drop_index(op.f('ix_outreach_templates_situation_id'), table_name='outreach_templates')
    op.drop_index(op.f('ix_outreach_templates_niche_id'), table_name='outreach_templates')
    op.drop_constraint(None, 'outreach_prospects', type_='foreignkey')
    op.drop_constraint(None, 'outreach_prospects', type_='foreignkey')
    op.drop_constraint(None, 'outreach_prospects', type_='foreignkey')
    op.create_index('uq_campaign_email', 'outreach_prospects', ['campaign_id', 'email'], unique=False, postgresql_where="((email IS NOT NULL) AND ((email)::text <> ''::text))")
    op.create_index('ix_outreach_prospects_status', 'outreach_prospects', ['status'], unique=False)
    op.alter_column('outreach_prospects', 'response_type',
               existing_type=sa.Enum('INTERESTED', 'NOT_INTERESTED', 'OTHER', name='responsetype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('outreach_prospects', 'status',
               existing_type=sa.Enum('QUEUED', 'IN_SEQUENCE', 'REPLIED', 'NOT_INTERESTED', 'CONVERTED', 'SKIPPED', 'PENDING_CONNECTION', 'CONNECTED', 'PENDING_ENGAGEMENT', name='prospectstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('outreach_campaigns', 'status',
               existing_type=sa.Enum('ACTIVE', 'ARCHIVED', name='campaignstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('outreach_campaigns', 'campaign_type',
               existing_type=sa.Enum('EMAIL', 'LINKEDIN', 'MULTI_TOUCH', name='campaigntype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'EMAIL'::character varying"))
    op.create_index('ix_loom_audits_sent_date', 'loom_audits', ['sent_date'], unique=False)
    op.alter_column('insights', 'sample_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('insights', 'confidence',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(None, 'experiments', type_='foreignkey')
    op.create_foreign_key('experiments_audit_id_fkey', 'experiments', 'audit_results', ['audit_id'], ['id'], ondelete='CASCADE')
    op.alter_column('experiments', 'step_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('experiments', 'angle_used')
    op.drop_column('experiments', 'cta_used')
    op.drop_index(op.f('ix_email_opens_id'), table_name='email_opens')
    op.alter_column('email_matches', 'received_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('email_matches', 'to_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('email_matches', 'from_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index('ix_discovery_calls_call_date', 'discovery_calls', ['call_date'], unique=False)
    op.drop_index(op.f('ix_crm_interactions_contact_id'), table_name='crm_interactions')
    op.drop_index(op.f('ix_crm_deals_contact_id'), table_name='crm_deals')
    op.alter_column('crm_deals', 'service_status',
               existing_type=sa.Enum('ACTIVE', 'PAUSED', 'CANCELLED', 'PENDING', name='servicestatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('crm_deals', 'billing_frequency',
               existing_type=sa.Enum('MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL', name='billingfrequency'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.create_table('coach_insights',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', postgresql.ENUM('ACTION', 'TIME', 'PATTERN', name='insighttype'), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='insightpriority'), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('suggested_action', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('action_params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seen', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('dismissed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='coach_insights_pkey')
    )
    op.create_index('ix_coach_insights_type', 'coach_insights', ['type'], unique=False)
    op.create_index('ix_coach_insights_seen', 'coach_insights', ['seen'], unique=False)
    op.create_index('ix_coach_insights_id', 'coach_insights', ['id'], unique=False)
    op.create_index('ix_coach_insights_dismissed', 'coach_insights', ['dismissed'], unique=False)
    op.create_index('ix_coach_insights_created_at', 'coach_insights', ['created_at'], unique=False)
    # ### end Alembic commands ###
